# Generated by Django 5.0.6 on 2025-04-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_photo_user_album_user_photo_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
